name: Continuous Deployment Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted # will run on EC2 Instance now.

    steps:
      - name: Pull Docker Image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: sudo docker pull $DOCKER_USER/lac-fastapi:latest

      - name: Delete Old Docker Container
        run: sudo docker rm -f lac-fastapi-container || true

      - name: Run Docker Container
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: sudo docker run -it -d -p 8001:8001 --name lac-fastapi-container $DOCKER_USER/lac-fastapi:latest
