name: Continuous Integration Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3 # Corrected syntax for checkout
      - name: Set up Python 3.10
        uses: actions/setup-python@v3 # Corrected syntax for setup-python
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements/requirements.txt

      - name: Train and save pipeline
        run: python src/train_pipeline.py

      - name: Upload Trained Pipeline
        uses: actions/upload-artifact@v3 # Corrected syntax for upload-artifact
        with:
          name: my-trained-pipeline
          path: src/trained_models/*.pkl
          retention-days: 1

  test:
    needs: train
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3 # Corrected syntax
      - name: Set up Python 3.10
        uses: actions/setup-python@v3 # Corrected syntax
        with:
          python-version: "3.10"

      - name: Download Trained Pipeline
        uses: actions/download-artifact@v3 # Corrected syntax
        with:
          name: my-trained-pipeline
          path: src/trained_models

      - name: Install test dependencies
        run: pip install -r requirements/test_requirements.txt

      - name: Test with pytest
        run: pytest

  build:
    needs: [train, test]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3 # Corrected syntax
      - name: Set up Python 3.10
        uses: actions/setup-python@v3 # Corrected syntax
        with:
          python-version: "3.10"

      - name: Download Trained Pipeline
        uses: actions/download-artifact@v3 # Corrected syntax
        with:
          name: my-trained-pipeline
          path: src/trained_models

      - name: Install build dependencies
        run: pip install --upgrade build

      - name: Build package
        run: python -m build

      - name: Upload Build Package
        uses: actions/upload-artifact@v3 # Corrected syntax
        with:
          name: my-build-package
          path: dist/*.whl
          retention-days: 1

  push-image:
    needs: [train, test, build]
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v3

      - name: Download Build Package
        uses: actions/download-artifact@v3
        with:
          name: my-build-package
          path: dist # Save the .whl file in the `dist` folder

      - name: Login to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS_TOKEN }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin

      - name: Build Docker Image for FastAPI App
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: docker build . -f Dockerfile -t $DOCKER_USER/lac-fastapi:latest

      - name: Push Docker Image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: docker push $DOCKER_USER/lac-fastapi

      - name: Logout from Docker Hub
        run: docker logout
