name: Continuous Integration Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements/requirements.txt

      - name: Train and save pipeline
        run: python src/train_pipeline.py

      - name: Upload Trained Pipeline
        uses: actions/upload-artifact@v3
        with:
          name: my-trained-pipeline
          path: src/trained_models/*.pkl
          retention-days: 1

  test:
    needs: train
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Download Trained Pipeline
        uses: actions/download-artifact@v3
        with:
          name: my-trained-pipeline
          path: src/trained_models

      - name: Install test dependencies
        run: pip install -r requirements/test_requirements.txt

      - name: Test with pytest
        run: pytest

  build:
    needs: [train, test]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Download Trained Pipeline
        uses: actions/download-artifact@v3
        with:
          name: my-trained-pipeline
          path: src/trained_models

      - name: Install build dependencies
        run: pip install --upgrade build

      - name: Build package
        run: python -m build

      - name: Upload Build Package
        uses: actions/upload-artifact
